### ISSUE TITLE
parcelも紹介してほしいです

### ISSUE THREAD

**Issue by rainy-me** [whatasoda/web-camp-2019#1]
https://parceljs.org を使ってみたらGulpより使いやすい気がします。😎

**Comment by whatasoda** [comment]
parcel、存在は知ってたけど使ったことなかったので調べて内容に盛り込もうと思います〜
ありがとう！！
もしよければ更新後レビューして欲しいです！

**Comment by whatasoda** [comment]
更新する時間なかったので当日ノリと勢いでやります

**Comment by rainy-me** [comment]
私が似なような例を作ってPRを送るのはどうですか

**Comment by whatasoda** [comment]
当日紹介する時間あるかも怪しいけど、
今余裕あるならお願いしたいです><

**Comment by rainy-me** [comment]
#2
